config: don't import grp on Windows platforms
On Windows, aiot-config fails with:
ModuleNotFoundError: No module named 'grp'

This is because the grp module is available for unix only [1].

Fix it by conditionally do the import.

Note that the usage of 'grp' is already done for linux-only.

[1] https://docs.python.org/3/library/grp.html
Fixes: 04ea06c ("Flashing documentation about the required Linux group")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>