ftdi_win: Remove mandatory dependency to FTDI DLL
It is possible that FTDI driver DLL is not installed on a Windows
system. Since FTDI board control works only on specific boards,
we should make this feature optional.

Handle exceptions during import ftd2xx to fix the following exceptions
when running `genio-flash` on a Windows host without FTDI drivers
installed:

Traceback (most recent call last):
  File "%APPDATA%\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "%APPDATA%\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "%APPDATA%\Local\Programs\Python\Python39\Scripts\genio-flash.exe\__main__.py", line 4, in <module>
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\aiot\__init__.py", line 18, in <module>
    from aiot.boardcontrol_win import BoardControl
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\aiot\boardcontrol_win.py", line 8, in <module>
    from aiot.ftdi_win import FtdiControl as FtdiControl
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\aiot\ftdi_win.py", line 23, in <module>
    import ftd2xx as ftd
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\ftd2xx\__init__.py", line 21, in <module>
    from .ftd2xx import (
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\ftd2xx\ftd2xx.py", line 19, in <module>
    from . import _ftd2xx as _ft
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\ftd2xx\_ftd2xx.py", line 97, in <module>
    raise e
  File "%APPDATA%\Local\Programs\Python\Python39\lib\site-packages\ftd2xx\_ftd2xx.py", line 87, in <module>
    _libraries["ftd2xx.dll"] = WinDLL("ftd2xx.dll")
  File "%APPDATA%\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'ftd2xx.dll' (or one of its dependencies). Try using the full path with constructor syntax.

CR-Id: ALPS09301016
Signed-off-by: Pablo Sun <pablo.sun@mediatek.com>